version: '3'

services:
  projdb:
    container_name: proj_db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rustweb
      - POSTGRES_PASSWORD=rustweb
      - POSTGRES_DB=finalproject
  projweb:
    container_name: proj_web
    build: ./backend/
    ports:
      - "80:3000"
    env_file:
      - ./backend/.env

volumes:
  db:
    driver: local

