version: '3'

services:
  finalproject:
    container_name: final_project
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rustweb
      - POSTGRES_PASSWORD=rustweb
      - POSTGRES_DB=finalproject
#  backend:
#    container_name: backend
#    build: ./backend/

volumes:
  db:
    driver: local

